### ISSUE TITLE
根据个人情况整理

### ISSUE THREAD

**Issue by iCirno** [2dust/androidpackagenamelist#2]
com.google.android.ims
com.google.android.youtube
com.google.android.gm
com.android.chrome
com.wire mark.via.gp
com.twitter.android
com.downloader.video.tumblr
com.sololearn
com.cygames.Shadowverse
com.FelixFilip.SCPAE
amanita_design.samorost3.GP
com.devolver.reigns2
com.utopia.pxview
ch.protonmail.android
com.google.android.play.games
com.perol.asdpl.pixivez
com.pinterest
com.paypal.android.p2pmobile
com.arthurivanets.owly
com.rubenmayayo.reddit
com.rayark.cytus2
com.rayark.pluto
com.rayark.implosion
com.FireproofStudios.TheRoom4
com.netflix.mediaclient
com.instagram.android
com.google.android.apps.hangoutsdialer
com.google.android.talk com.google.android.apps.plus com.google.android.apps.pdfviewer
com.google.android.apps.magazines
com.google.android.apps.nbu.files
com.evernote
net.tsapps.appsales
com.google.android.apps.translate
com.google.ar.lens
com.google.android.apps.adm
com.google.android.apps.googleassistant
tw.com.gamer.android.activecenter
org.telegram.plus
com.brave.browser
com.breel.wallpapers18
com.teslacoilsw.launcher
com.lastpass.lpandroid
org.kustom.widget
com.google.android.inputmethod.latin
com.fooview.android.fooview
com.android.vending
com.google.android.apps.docs
com.google.android.apps.photos com.google.android.apps.maps
com.spotify.music
com.facebook.services
com.facebook.system
com.facebook.katana

**Comment by 2dust** [comment]
ok
