### ISSUE TITLE
Need proxy on android

### ISSUE THREAD

**Issue by NicolasKun** [2dust/androidpackagenamelist#3]
jp.pxv.android
com.quora.android
com.lingodeer
com.google.android.inputmethod.latin
com.reddit.frontpage
com.instagram.android
org.wikipedia
com.ninegag.android.app
com.duolingo
com.patreon.android
com.google.*
com.valvesoftware.android.steam.communimunity
co.wanqu.Android
jp.bokete.app.android

**Comment by NicolasKun** [comment]
com.vkontakte.android
com.amazon.mShop.android.shopping

**Comment by NicolasKun** [comment]
com.instagram.android
com.ubisoft.dance.justdance2015companion
com.tumblr
com.gameloft.android.ANMP.GloftA8HM
com.gameloft.android.ANMP.GloftA9HM
org.telegram.messenger

**Comment by NicolasKun** [comment]
Thanks !

**Comment by 2dust** [comment]
ok
