### ISSUE TITLE
个人分应用代理app

### ISSUE THREAD

**Issue by gaxdel** [2dust/androidpackagenamelist#5]
com.nianticlabs.ingress.prime.qa
com.vanced.android.youtube
com.nianticproject.ingress
com.rayark.cytus2
com.netflix.mediaclient
com.android.chrome
com.quoord.tapatalkpro.activity
org.mozilla.firefox
com.reddit.frontpage
com.google.android.apps.fitness
com.google.android.gm
com.google.android.apps.docs
au.com.shiftyjelly.pocketcasts
com.google.android.gms
org.thunderdog.challegram
com.google.android.apps.photos
com.google.android.apps.translate
com.android.providers.telephony
com.android.vending
com.google.android.googlequicksearchbox
com.resilio.sync
com.google.android.apps.googlevoice
com.discord
com.google.android.keep
com.cradle.iitc_mobile
com.google.android.play.games

**Comment by 2dust** [comment]
ok
