### ISSUE TITLE
个人需代理的列表

### ISSUE THREAD

**Issue by Furthermorer** [2dust/androidpackagenamelist#6]
com.chrome.dev
com.binance.dev
com.asahi.tida.tablet
com.theinitium.news
com.driverbrowser
com.thomsonreuters.reuters
com.nytimes.cn
org.wikipedia
com.android.providers.downloads.ui
com.apkpure.aegon
com.avmovie
bbc.mobile.news.ww
org.mozilla.firefox
org.mozilla.focus
flipboard.app
com.innologica.inoreader
com.instagram.android
io.github.javiewer
com.sonelli.juicessh
com.ubisoft.dance.justdance2015companion
con.medium.reader
com.netflix.mediaclient
com.microsoft.skydrive
org.torproject.android
com.pinterest
es.rafalense.themes
au.com.shiftyjelly.pocketcasts
com.app.pornhub
com.quora.android
com.reddit.frontpage
com.valvesoftware.android.steam.community
com.nintendo.zara
org.thunderdog.challegram
org.torproject.torbrowser_alpha
com.tumblr
tv.twitch.android.app
com.twitter.android
mark.via.gp
com.shanga.walli
com.whatsapp
com.wire
com.google.android.youtube
org.telegram.plus
com.simplehabit.simplehabitapp

**Comment by 2dust** [comment]
ok
