### ISSUE TITLE
建议添加的一些包名

### ISSUE THREAD

**Issue by ddkisss** [2dust/androidpackagenamelist#9]
com.google.android.street
com.flyersoft.moonreaderp
io.github.skyhacker2.magnetsearch
com.authy.authy
com.ninefolders.hd3
com.tripadvisor.tripadvisor

谢谢。

**Comment by 2dust** [comment]
ok

**Comment by trivita** [comment]
com.ninefolders.hd3 是个邮件应用，这个不用吧。。

**Comment by ddkisss** [comment]
> com.ninefolders.hd3 是个邮件应用，这个不用吧。。

嗯，比如通过nine链接类似gmail这样的邮件商时是需要的，或者接收一些被**的网站发来的带有外链图片等复杂排版的邮件时，不设置的话是显示不全邮件内容的。此外nine代理之后，同步任务、通讯录、和工作日程会更稳定。
